core/urls.py
from django.urls import path, include

from core.views import *

urlpatterns = [
    path('', GoodLoginView.as_view(), name='home'),
    path('login/', GoodLoginView.as_view(), name='login'),

    path('items/', ItemListView.as_view(), name='item_list'),
    path('items/add/', ItemCreateView.as_view(), name='item_add'),
    path('items/<int:pk>', ItemDetailView.as_view(), name='item'),
    path('items/<int:pk>/sold/', SoldView.as_view(), name='item_sold'),
    path('items/<int:pk>/change-status/', ChangeStatusView.as_view(), name='item_change_status'),
]

good_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from good_crm import settings

urlpatterns = [
    path('', include('core.urls')),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django import forms
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

STATUS_CHOICES = (
    (1, _("есть в наличии")),
    (2, _("ожидает поступления")),
    (3, _("нет в наличии"))
)


def set_right_status(item):
    if item.number > 0:
        item.status = 1
    else:
        item.status = 3
    return item


class Item(models.Model):
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['id']
        permissions = (
            ("can_sold_items", "Продать товар"),
            ("can_change_status", "Поменять статус"),
        )

    name = models.CharField(max_length=50, null=True, verbose_name=_('Товар'))
    status = models.IntegerField(choices=STATUS_CHOICES, default=3, verbose_name=_('Статус'))
    number = models.PositiveIntegerField(default=0, verbose_name=_('Количество'))

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('item', kwargs={'pk': self.pk})


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

    def save(self, commit=True):
        item = super(ItemForm, self).save(commit=False)
        item = set_right_status(item)
        if commit:
            item.save()
        return item


class SoldForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = []

    number = forms.IntegerField(min_value=0, required=True)


class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['status']

core/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission, Group
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, ListView, CreateView, DetailView, UpdateView

from .models import *


add_item_permission = Permission.objects.get(codename='add_item')
sold_permission = Permission.objects.get(name='Продать товар')
change_status_permission = Permission.objects.get(name='Поменять статус')

provider, created = Group.objects.get_or_create(name='поставщик')
employee_group, created = Group.objects.get_or_create(name='сотрудник склада')

# Сотрудник склада: может только пользоваться кнопкой “Продали”.
employee_group.permissions.set([sold_permission])
# Поставщик: может только добавлять товары и менять статус на “Ожидает поступления”,
# если у наименования статус “Нет в наличии”.
provider.permissions.set([change_status_permission, add_item_permission])

# Завсклад: может добавлять, удалять и редактировать товары. Может выставлять все статусы для наименований.
# Может выставлять количество товара на складе. Завсклад может создавать новых пользователей и выставлять им роли.


class GoodLoginView(LoginView):
    template_name = 'sign-in.html'

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse('admin:index')
        return reverse('item_list')


class ItemListView(ListView):
    model = Item
    template_name = 'item-list.html'


class ItemDetailView(DetailView):
    model = Item
    template_name = 'item.html'


class ItemCreateView(PermissionRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    template_name = 'create_item.html'
    success_url = reverse_lazy('item_list')
    permission_required = ('core.add_item',)


class SoldView(PermissionRequiredMixin, UpdateView):
    '''У каждого товара есть кнопка “Продали”, нажатие на которую вызывает форму,
    в которой можно указать количество проданного товара и нажать кнопку “Ок”.
    После нажатия на кнопку “Продали”, от количества товара на складе должно отниматься число,
    которое указали в окне “Продали”. Нельзя продать больше, чем есть на складе.'''
    model = Item
    form_class = SoldForm
    template_name = 'change_number.html'
    success_url = reverse_lazy('item_list')
    permission_required = ('core.can_sold_items',)

    def form_valid(self, form):
        response = super(SoldView, self).form_valid(form)
        self.object.number -= form.cleaned_data['number']
        set_right_status(self.object)
        self.object.save()
        return response


class ChangeStatusView(PermissionRequiredMixin, UpdateView):
    model = Item
    fields = []
    template_name = 'item-list.html'
    success_url = reverse_lazy('item_list')
    permission_required = ('core.can_change_status',)
    
    def form_valid(self, form):
        self.object.status = 2
        self.object.save()
        return super(ChangeStatusView, self).form_valid(form)

templates/base.html
{% load static widget_tweaks %}
<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="container">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'item_list' %}">Список товаров</a>
        </li>
      </ul>
        </div>
    </div>
  </nav>
  <div class="container">

    {% block content %}{% endblock %}
  </div>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  {% block js %}{% endblock %}
</body>
</html>

templates/change_number.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block content %}
  <div class="row">
    <form method="post">
      <h4>Продать {{ item.name }}</h4>
      {% csrf_token %}
      <div class="form-group">
        <label for="id_number">{{ form.number.label }}</label>
        {% render_field form.number class="form-control" max=item.number %}
      </div>
      <button type="submit" class="btn btn-primary">Ok</button>
    </form>
  </div>
{% endblock %}

templates/create_item.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block content %}
  <div class="row">
    <form method="post">
      <h4>Создать товар</h4>
      {% csrf_token %}
      <div class="form-group">
        <label for="id_name">{{ form.name.label }}</label>
        {% render_field form.name class="form-control" placeholder='Название товара ' %}
      </div>
      <div class="form-group">
        <label for="id_number">{{ form.number.label }}</label>
        {% render_field form.number class="form-control" %}
      </div>
      <div class="form-group">
        <label for="id_status">{{ form.status.label }}</label>
        {% render_field form.status class="form-control"%}
      </div>
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
  </div>
{% endblock %}

templates/item-list.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block content %}
  <h3>Список товаров</h3>
  <div class="pb-1">
    {% if perms.core.add_item %}
      <a class="btn btn-outline-primary" href="{% url 'item_add' %}">Добавить товар</a>
    {% endif %}
  </div>
  <table class="table align-content-center align-middle">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Статус</th>
        <th scope="col">Количество</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    {% for item in item_list %}
      <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.get_status_display }}</td>
        <td>{{ item.number }}</td>
        <td>
          {% if perms.core.can_sold_items and item.number > 0 %}
            <a class="btn btn-sm btn-outline-primary" href="{% url 'item_sold' item.pk %}">Продать товар</a>
          {% endif %}
          {% if perms.core.can_change_status and item.status == 3 %}
            <form action="{% url 'item_change_status' item.pk %}" method="post"> {% csrf_token %}
              <button class="btn btn-sm btn-outline-primary" type="submit">Поменять статус на ожидает поступления</button>
            </form>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/item.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block content %}
  <h3>Товар: {{ item.name }}</h3>
  <p>Статус: {{ item.status }}</p>
  <p>Количество: {{ item.number }}</p>
{% endblock %}

templates/sign-in.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block content %}
  <div class="row">
    <form method="post">
      <h4>Вход</h4>
      {% csrf_token %}
      <div class="form-group">
        <label for="id_username">Имя пользователя</label>
        {% render_field form.username class="form-control" placeholder="Имя пользователя" %}
      </div>
      <div class="form-group">
        <label for="id_password">Пароль</label>
        {% render_field form.password class="form-control" placeholder="Пароль" %}
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
  </div>
{% endblock %}